# Alternative: Direct Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cyberpunk-rs
  namespace: 'your-project-id'
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      containers:
      - image: gcr.io/your-project-id/cyberpunk-rs:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: APP_ENVIRONMENT
          value: production
        - name: APP_APPLICATION__HOST
          value: 0.0.0.0
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10