# Fly.io configuration for ultra-low-cost deployment
app = "cyberpunk-rs"
primary_region = "ord" # Chicago - good latency for US
kill_signal = "SIGINT"
kill_timeout = "30s"

[experimental]
auto_rollback = true

[build]

[[mounts]]
source = "cyberpunk_data"
destination = "/data"
initial_size = "1gb"      # Very small persistent volume

[env]
APP_ENVIRONMENT = "production"
APP_APPLICATION__HOST = "0.0.0.0"
APP_APPLICATION__PORT = "8080"
APP_STORAGE__BASE_DIR = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0   # Scale to zero!
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024    # Start small, can scale up

[http_service.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20

# Health check for auto-scaling
[checks]
[checks.health]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/health"
port = 8080
timeout = "5s"
type = "http"

# Scale to zero configuration
[deploy]
strategy = "immediate"
