application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
storage:
  base_dir: /Users/johannes/Repos/cyberpunk-rs
  path_prefix: testdata/
custom_tags:
  env: local
processor:
  max_filter_ops: 256
  concurrency: 1
  max_cache_files: 0
  max_cache_mem: 0
  max_cache_size: 0
cache:
  filesystem:
    base_dir: /Users/johannes/Repos/cyberpunk-rs/cache
